version: 1
disable_existing_loggers: False

formatters:
  simple_request:
    format: "{{\"timestamp\":\"{asctime}\", \"level\":\"{levelname}\", \"name\":\"{name}\", \"message\":\"{message}\"}}"
    style: '{'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple_request
    stream: ext://sys.stdout
    filters: [ ]

root:
  level: INFO
  handlers: [ console ]
